name: after_layout
description: Run code in your widgets the first time they are ready.
version: 1.0.0
author: Simon Lightfoot <simon@devangels.london>
homepage: https://github.com/slightfoot/flutter_after_layout

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
